baseurl = "https://blog.iuliancostan.com"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
title = "Decentralized meta-learning"
canonifyurls  = true
DefaultContentLanguage = "en"
theme = "beautifulhugo"
metaDataFormat = "yaml"
summaryLength = 16

pygmentsUseClasses = true
pygmentsStyle = "monokai"
pygmentsCodeFences = true
# pygmentsCodefencesGuessSyntax = true
# pygmentsUseClassic = true
# pygmentsOptions = "linenos=inline"

disqusShortname = "icostan"
googleAnalytics = "UA-354095-4"

[Params]
  subtitle = "The hard way, the easy way"
  logo = "img/avatar.jpg"
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = false
  # socialShare = true
  # delayDisqus = true
  # showRelatedPosts = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[Author]
  name = "Iulian Costan"
  email = "blog@iuliancostan.com"
  facebook = "iuliancostan"
  # googleplus = "+username" # or xxxxxxxxxxxxxxxxxxxxx
  gitlab = "icostan"
  github = "icostan"
  twitter = "iuliancostan"
  reddit = "icostan"
  linkedin = "iuliancostan"
  # xing = "username"
  stackoverflow = "users/4423469/icostan"
  # snapchat = "username"
  instagram = "iuliancostan"
  youtube = "c/iuliancostan" # or channel/channelname
  # soundcloud = "username"
  spotify = "iuliancostan"
  # bandcamp = "username"
  # itchio = "username"
  keybase = "icostan"
  kaggle = "icostan"


[[menu.main]]
    identifier = "crypto"
    name = "Crypto"
    weight = 1
[[menu.main]]
    parent = "crypto"
    name = "RSA"
    url = "post/2019-03-16-rsa"
    weight = 1
[[menu.main]]
    parent = "crypto"
    name = "ElGamal"
    url = "post/2019-03-26-elgamal"
    weight = 2
[[menu.main]]
    parent = "crypto"
    name = "ECDSA"
    url = "post/2019-04-09-ecdsa"
    weight = 3
[[menu.main]]
    parent = "crypto"
    name = "Schnorr"
    url = "post/2019-06-19-schnorr"
    weight = 4
[[menu.main]]
    parent = "crypto"
    name = "EC-Schnorr"
    url = "post/2019-06-25-ec-schnorr"
    weight = 5
[[menu.main]]
    parent = "crypto"
    name = "Zero knowledge proofs"
    url = "post/2019-08-26-zero-knowledge-proofs"
    weight = 6
[[menu.main]]
    parent = "crypto"
    name = "Elliptic curves"
    url = "post/2019-09-25-elliptic-curves"
    weight = 7
[[menu.main]]
    parent = "crypto"
    name = "Commitment schemes"
    url = "post/2020-02-25-commitment-schemes"
    weight = 8

[[menu.main]]
    identifier = "emacs"
    name = "Emacs"
    weight = 2
[[menu.main]]
    parent = "emacs"
    name = "Buffer navigation"
    url = "post/2019-11-07-emacs-in-file-navigation"
    weight = 1
[[menu.main]]
    parent = "emacs"
    name = "Windows navigation"
    url = "post/2020-04-04-emacs-file-window-buffer-navigation"
    weight = 2

[[menu.main]]
    identifier = "linux"
    name = "Linux"
    weight = 3
[[menu.main]]
    parent = "linux"
    name = "Back to my first love"
    url = "post/2019-07-05-back-to-my-first-love/"
    weight = 1
[[menu.main]]
    parent = "linux"
    name = "Package management"
    url = "post/2019-09-10-package-management"
    weight = 2
[[menu.main]]
    parent = "linux"
    name = "Config management"
    url = "post/2019-10-22-configuration-management"
    weight = 3
[[menu.main]]
    parent = "linux"
    name = "Linux kernel module"
    url = "post/2020-03-24-write-linux-kernel-module"
    weight = 4

[[menu.main]]
    identifier = "opensource"
    name = "OSS"
    weight = 4
[[menu.main]]
    parent = "opensource"
    name = "Bitmex-API"
    url = "post/2019-01-27-bitmex-api-ruby"
    weight = 1
[[menu.main]]
    parent = "opensource"
    name = "Actihunt"
    url = "post/2019-02-14-opensourcing-actihunt"
    weight = 2
[[menu.main]]
    parent = "opensource"
    name = "Deribit-API"
    url = "post/2019-05-03-deribit-api-ruby"
    weight = 3
[[menu.main]]
    parent = "opensource"
    name = "3DP"
    url = "post/2019-07-18-3dp"
    weight = 3

[[menu.main]]
    identifier = "nomad"
    name = "Nomad"
    weight = 5
[[menu.main]]
    parent = "nomad"
    name = "Surviving Bali"
    url = "post/2019-11-19-surviving-bali"
    weight = 1
[[menu.main]]
    parent = "nomad"
    name = "Backpacking Viet Nam"
    url = "post/2019-12-21-backpacking-vietnam"
    weight = 2
[[menu.main]]
    parent = "nomad"
    name = "Diving Palawan"
    url = "post/2020-01-21-diving-palawan"
    weight = 3

[[menu.main]]
    identifier = "trading"
    name = "Trading"
    weight = 6
[[menu.main]]
    parent = "trading"
    name = "Weekly Monthly Close"
    url = "post/2019-02-28-weekly-monthly-close"
    weight = 1
[[menu.main]]
    parent = "trading"
    name = "Slices of Bitcoin"
    url = "post/2019-05-31-slices-of-bitcoin"
    weight = 2
[[menu.main]]
    parent = "trading"
    name = "Month Breaks"
    url = "post/2019-12-16-month-breaks"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 7

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 8
