baseurl = "https://blog.costan.ro"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
title = "Decentralized meta-learning"
canonifyurls  = true
DefaultContentLanguage = "en"
theme = "beautifulhugo"
metaDataFormat = "yaml"
summaryLength = 16

pygmentsUseClasses = true
pygmentsStyle = "monokai"
pygmentsCodeFences = true
# pygmentsCodefencesGuessSyntax = true
# pygmentsUseClassic = true
# pygmentsOptions = "linenos=inline"

disqusShortname = "icostan"
# googleAnalytics = "UA-354095-4"

[Params]
  subtitle = "The hard way, the easy way"
  logo = "img/avatar.jpg"
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = false
[Params.huveragy]
  home = "RO"
  colors = ['#dc9658', '#d62728']
  countries = { "AE"=1, "AR"=1, "AU"=1, "BG"=2, "BR"=1, "CY"=1, "DK"=1, "EG"=1, "ES"=1, "FI"=1, "FR"=2, "GB"=3, "GR"=3, "HU"=3, "ID"=1, "IN"=2, "IT"=3, "JP"=1, "LV"=1, "MD"=3, "MY"=2, "MV"=1, "NO"=1, "PH"=1, "PK"=1, "RO"=5, "RU"=3, "QA"=1, "SE"=1, "SG"=2, "TH"=2, "TN"=1, "TR"=1, "TZ"=1, "UA"=3, "UK"=2, "US"=5, "VN"=1 }

  # socialShare = true
  # delayDisqus = true
  # showRelatedPosts = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[Author]
  name = "Iulian Costan"
  email = "blog@costan.ro"
  facebook = "iuliancostan"
  # googleplus = "+username" # or xxxxxxxxxxxxxxxxxxxxx
  gitlab = "icostan"
  github = "icostan"
  twitter = "iuliancostan"
  reddit = "icostan"
  linkedin = "iuliancostan"
  # xing = "username"
  stackoverflow = "users/4423469/icostan"
  # snapchat = "username"
  instagram = "iuliancostan"
  youtube = "c/iuliancostan" # or channel/channelname
  # soundcloud = "username"
  spotify = "iuliancostan"
  # bandcamp = "username"
  # itchio = "username"
  keybase = "icostan"
  kaggle = "icostan"

[[menu.main]]
    identifier = "bitcoin"
    name = "Bitcoin"
    weight = 1
[[menu.main]]
    parent = "bitcoin"
    name = "4. Segwit transaction"
    url = "post/2021-11-25-bitcoin-segwit-transaction/"
    weight = 1
[[menu.main]]
    parent = "bitcoin"
    name = "3. Segwit address"
    url = "post/2020-02-10-bitcoin-bech32-segwit-address/"
    weight = 2
[[menu.main]]
    parent = "bitcoin"
    name = "2. Bitcoin transaction"
    url = "post/2018-11-11-bitcoin-transaction/"
    weight = 3
[[menu.main]]
    parent = "bitcoin"
    name = "1. Bitcoin address"
    url = "post/2018-10-09-bitcoin-address/"
    weight = 4

[[menu.main]]
    identifier = "cryptography"
    name = "Cryptography"
    weight = 10
[[menu.main]]
    parent = "cryptography"
    name = "RSA"
    url = "post/2019-03-16-rsa"
    weight = 1
[[menu.main]]
    parent = "cryptography"
    name = "ElGamal"
    url = "post/2019-03-26-elgamal"
    weight = 2
[[menu.main]]
    parent = "cryptography"
    name = "ECDSA"
    url = "post/2019-04-09-ecdsa"
    weight = 3
[[menu.main]]
    parent = "cryptography"
    name = "Schnorr"
    url = "post/2019-06-19-schnorr"
    weight = 4
[[menu.main]]
    parent = "cryptography"
    name = "EC-Schnorr"
    url = "post/2019-06-25-ec-schnorr"
    weight = 5
[[menu.main]]
    parent = "cryptography"
    name = "Zero knowledge proofs"
    url = "post/2019-08-26-zero-knowledge-proofs"
    weight = 6
[[menu.main]]
    parent = "cryptography"
    name = "Elliptic curves"
    url = "post/2019-09-25-elliptic-curves"
    weight = 7
[[menu.main]]
    parent = "cryptography"
    name = "Commitment schemes"
    url = "post/2020-02-25-commitment-schemes"
    weight = 8
[[menu.main]]
    parent = "cryptography"
    name = "Hash functions"
    url = "post/2020-09-15-hash-functions"
    weight = 9

[[menu.main]]
    identifier = "coins"
    name = "Coins"
    weight = 20
[[menu.main]]
    parent = "coins"
    name = "Ethereum address"
    url = "post/2020-10-27-generate-ethereum-address"
    weight = 1
[[menu.main]]
    parent = "coins"
    name = "Monero address"
    url = "post/2020-07-18-generate-monero-address"
    weight = 2
[[menu.main]]
    parent = "coins"
    name = "Iota address"
    url = "post/2020-12-28-generate-iota-address"
    weight = 3

[[menu.main]]
    identifier = "finance"
    name = "Finance"
    weight = 40
[[menu.main]]
    parent = "finance"
    name = "Interest Rate"
    url = "post/2020-11-24-interest-rate"
    weight = 1
[[menu.main]]
    parent = "finance"
    name = "Black-Scholes formula"
    url = "post/2021-01-28-black-scholes-formula"
    weight = 2
[[menu.main]]
    parent = "finance"
    name = "Options Greeks"
    url = "post/2021-02-16-options-greeks"
    weight = 3
[[menu.main]]
    parent = "finance"
    name = "Historical Volatility"
    url = "post/2021-03-17-historical-volatility"
    weight = 4
[[menu.main]]
    parent = "finance"
    name = "Returns, metrics"
    url = "post/2021-09-14-returns-risk-adjusted-ratios-metrics/"
    weight = 5

[[menu.main]]
    identifier = "linux"
    name = "Linux"
    weight = 50
[[menu.main]]
    parent = "linux"
    name = "3. Use Linux kernel module"
    url = "post/2021-09-30-use-linux-kernel-module"
    weight = 1
[[menu.main]]
    parent = "linux"
    name = "2. Config Linux kernel module"
    url = "post/2020-08-25-configure-linux-kernel-module"
    weight = 2
[[menu.main]]
    parent = "linux"
    name = "1. Write Linux kernel module"
    url = "post/2020-03-24-write-linux-kernel-module"
    weight = 3
[[menu.main]]
    parent = "linux"
    name = "From HDD to SSD w/ EFI"
    url = "post/2021-12-21-from-hdd-to-ssd-with-efi-boot"
    weight = 4
[[menu.main]]
    parent = "linux"
    name = "Back to my first love"
    url = "post/2019-07-05-back-to-my-first-love/"
    weight = 5
[[menu.main]]
    parent = "linux"
    name = "Package management"
    url = "post/2019-09-10-package-management"
    weight = 6
[[menu.main]]
    parent = "linux"
    name = "Config management"
    url = "post/2019-10-22-configuration-management"
    weight = 7

[[menu.main]]
    identifier = "math"
    name = "Math"
    weight = 60
[[menu.main]]
    parent = "math"
    name = "Complexities with graphs"
    url = "post/2020-06-04-bigo-complexity-with-graphs"
    weight = 1
[[menu.main]]
    parent = "math"
    name = "Algebraic structures"
    url = "post/2020-11-11-algebraic-structures-set-group-ring"
    weight = 2
[[menu.main]]
    parent = "math"
    name = "Ternary (Trinary) system"
    url = "post/2020-12-30-ternary-trinary-binary-systems"
    weight = 3
[[menu.main]]
    parent = "math"
    name = "Bias vs. variance"
    url = "post/2021-03-30-bias-vs-variance"
    weight = 4

[[menu.main]]
    identifier = "opensource"
    name = "Open Source"
    weight = 70
[[menu.main]]
    parent = "opensource"
    name = "Bitmex-API"
    url = "post/2019-01-27-bitmex-api-ruby"
    weight = 1
[[menu.main]]
    parent = "opensource"
    name = "Actihunt"
    url = "post/2019-02-14-opensourcing-actihunt"
    weight = 2
[[menu.main]]
    parent = "opensource"
    name = "Deribit-API"
    url = "post/2019-05-03-deribit-api-ruby"
    weight = 3
[[menu.main]]
    parent = "opensource"
    name = "3DP"
    url = "post/2019-07-18-3dp"
    weight = 4
[[menu.main]]
    parent = "opensource"
    name = "Huveragy"
    url = "post/2020-04-27-huveragy"
    weight = 5
[[menu.main]]
    parent = "opensource"
    name = "G2: web app"
    url = "post/2021-08-27-gasherbrum2-webapp/"
    weight = 6

[[menu.main]]
    identifier = "trading"
    name = "Trading"
    weight = 80
[[menu.main]]
    parent = "trading"
    name = "Weekly Monthly Close"
    url = "post/2019-02-28-weekly-monthly-close"
    weight = 1
[[menu.main]]
    parent = "trading"
    name = "Slices of Bitcoin"
    url = "post/2019-05-31-slices-of-bitcoin"
    weight = 2
[[menu.main]]
    parent = "trading"
    name = "Month Breaks"
    url = "post/2019-12-16-month-breaks"
    weight = 3
[[menu.main]]
    parent = "trading"
    name = "COVID-19 indicators"
    url = "post/2020-05-07-covid-19-indicators"
    weight = 4
[[menu.main]]
    parent = "trading"
    name = "Hedge Fund Market Wizards book"
    url = "post/2020-07-28-hedge-fund-market-wizards-book"
    weight = 5
[[menu.main]]
    parent = "trading"
    name = "Session breaks"
    url = "post/2020-10-09-session-breaks"
    weight = 6
[[menu.main]]
    parent = "trading"
    name = "Whale alert"
    url = "post/2021-02-27-whale-alert"
    weight = 7
[[menu.main]]
    parent = "trading"
    name = "New Market Wizards book"
    url = "post/2021-04-07-new-market-wizards-book"
    weight = 8
[[menu.main]]
    parent = "trading"
    name = "Price breaks indicator"
    url = "/post/2021-10-16-price-hlc-breaks-indicator/"
    weight = 8
[[menu.main]]
    parent = "trading"
    name = "Chess vs Trading"
    url = "/post/2022-01-11-chess-vs-trading/"
    weight = 9

[[menu.main]]
    identifier = "travel"
    name = "Travel"
    weight = 85
[[menu.main]]
    parent = "travel"
    name = "4. G2: aftermath"
    url = "post/2021-08-12-gasherbrum2-aftermath/"
    weight = 1
[[menu.main]]
    parent = "travel"
    name = "3. G2: compare gear"
    url = "post/2021-05-27-gasherbrum2-how-to-compare-gear/"
    weight = 2
[[menu.main]]
    parent = "travel"
    name = "2. G2: gear list"
    url = "post/2021-05-10-gasherbrum2-gear-list/"
    weight = 3
[[menu.main]]
    parent = "travel"
    name = "1. G2: training plan"
    url = "post/2021-04-15-gasherbrum2-training-plan/"
    weight = 4
[[menu.main]]
    parent = "travel"
    name = "First USA visit"
    url = "post/2020-09-25-first-usa-visit/"
    weight = 5
[[menu.main]]
    parent = "travel"
    name = "Coworking spaces"
    url = "post/2020-06-24-outpost-toong-clockin-coworking/"
    weight = 6
[[menu.main]]
    parent = "travel"
    name = "High-end Maldives"
    url = "post/2020-05-23-high-end-maldives/"
    weight = 7
[[menu.main]]
    parent = "travel"
    name = "Diving Palawan"
    url = "post/2020-01-21-diving-palawan/"
    weight = 8
[[menu.main]]
    parent = "travel"
    name = "Backpacking Vietnam"
    url = "post/2019-12-21-backpacking-vietnam/"
    weight = 9
[[menu.main]]
    parent = "travel"
    name = "Surviging Bali"
    url = "post/2019-11-19-surviving-bali/"
    weight = 10

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 90

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 100
