#+title:  Surviving Bali
#+subtitle: Nomad
#+date:   2019-11-19
#+tags[]: nomad indonesia bali ubud

  I survived a month in Ubud, Bali, Indonesia with 2112 EUR :) I like the word survive but there is nothing to survive in Bali, especially in Ubud.

  Actually it is the opposite, it is very easy to live, a soft landing and relative cheap destination for both nomads/tourists.

  If I have to choose top 3 things in Ubud I would say:

  1. nature - vegetation, hills and impressive landscapes
  2. yoga - many schools in all shapes and sizes
  3. diversity - lots and lots of food/drink/stay options

** Expenses
   My initial budget was 1500 EUR (including the long flight) which was completely ruined but I will do better next time :).

   Here are all expenses grouped by top level accounts:

    #+begin_example
             2112.02 EUR  Expenses
              760.33 EUR    Accommodation
                1.05 EUR    Bank
               24.31 EUR    Clothing
              181.70 EUR    Coworking
              187.98 EUR    Drinks
              146.18 EUR      Alcohol
                9.62 EUR      Coffee
               21.77 EUR      N/A
                0.98 EUR      Tea
                9.42 EUR      Water
              204.10 EUR    Food
               13.98 EUR      Burger
                6.31 EUR      Desert
                3.25 EUR      Fajitas
                3.90 EUR      Fish
                1.30 EUR      Focaccia
               13.39 EUR      Fruits
               19.50 EUR      Japanese
                7.80 EUR      Pasta
               23.92 EUR      Pizza
                8.45 EUR      Salad
                4.81 EUR      Snack
                6.31 EUR      Soup
                9.95 EUR      Tax
                2.08 EUR      Tip
                3.25 EUR    Haircut
                7.93 EUR    Laundry
               12.02 EUR    Phone
                5.20 EUR    SPA:Massage
              127.86 EUR    Sports
                3.25 EUR      Surfing
              124.61 EUR      Yoga
               19.30 EUR    Toiletries
               16.05 EUR      Suncream
              576.98 EUR    Transportation
              485.00 EUR      Airplane
               91.98 EUR      Taxi
    --------------------
             2112.02 EUR
    #+end_example

   Alcohol is quite expensive, 2 EUR for a small beer (330ml) or 6 EUR for a cocktail pretty much everywhere but food prices are in different ranges:
   1. low cost: 2 EUR - traditional Nasi/Mia Goreng (fried rice/noodle with chicken/vegetable)
   2. mid range: 4 EUR - other traditional meals or salads
   3. high range: 6 EUR - pizza/pasta, tacos, international cuisines or vegetarian options
   4. expensive: more than 10 EUR - beef steaks or fancy restaurants

** Coworking
   There are two main coworking hubs in Ubud and besides these, there are plenty of fancy cafes, bigger or smaller with good internet, perfect spots for couple of hours of work everyday.

   1. [[https://destinationoutpost.co/][Outpost]] - the space is very nice with open and loud space upstairs and AC and very quite space downstairs. Internet was good (maybe except one evening when it was sluggish) and I constantly got around 30 Mbps download and upload.
   2. [[https://hubud.org/][Hubud]] - this is the big brother in town that was recently acquired by the same investors that own the famous [[https://www.dojobali.orga/][Dojo]] coworking space. A bit smaller than Outpost but nicely decorated in wooden traditional Balinese style with plenty of events every week and very active community.

   Outpost was my choice and I got coworking/coliving package for 900 EUR / month (coliving: 720 EUR/m, coworking: 180 EUR/m) just to see how everything works out. Not the best decision but I learn on the fly.

** Coliving
   Outpost has 3 coliving locations, I stayed in the Villas and only visited the Suites.

   1. Outpost Villas - this place does not really belong to Outpost, 4 villas with two rooms each (one upstairs, one downstairs) are rented from [[https://suartiubudresort.com/][Suarti Resort]] and sub-rented to Outpost customers. The resort itself and villas are nice but is not much of a coliving thing.
   2. Outpost Suites - this one is the real Outpost coliving location and is nicely positioned near Monkey Forest and the center of Ubud.
   3. Outpost Penestanan - [[https://www.roam.co/][Roam]] coworking/coliving went out of business and Outpost got the place and they are renovating/branding it and is scheduled to be officially opened in Dec 2019.

** Yoga
   The entire Bali island is popular yoga destination and Ubud being the top with many schools spread across the entire city.
   1. [[http://ubudyogacentre.com/][Ubud Yoga Center]] - this was the closest to my coworking space and it turned out to be a good choice in the end. A medium size Yoga school with 3 rooms and Bikram, Hatha, Vinyasa, Ashtanga, Kundalini yoga classes and also meditation, breathwork, sound healing sessions. They offer unlimited monthly access plan and there is also a very nice restaurant with vegan/vegetarian options for yogis.
   2. [[https://www.theyogabarn.com/][Yoga Barn]] - the biggest and the most famous Yoga school in Ubud very close to well known Monkey Forest. I went there once and I did not really like the yoga class. The room was huge, with 50+ people, quite noise and with so many people around you hardly get any correction. I am not sure about intermediate/advanced classes but for sure this school is not for beginners. Besides this, the entire Yoga barn area is very nice, cafe, restaurant, multiple ponds and villas for people who want to stay on-site.
   3. [[http://www.taksuyoga.com/][Taksu Yoga]] - very small Yoga school, a single room and only 3 or 4 classes a day but it is the most beautiful one. Actually Taksu is a SPA center, built on a small river bank right in the Ubud city center.

** Sea side

   I've been in Canggu (west of Bali island) for a long weekend and I can say that it deserves the reputation for parties/drinking and surf and this is pretty much it.

** Mountain side

   I climbed [[https://en.wikipedia.org/wiki/List_of_mountains_in_Bali][Batukaru]] mountain (2276m) in Bedugul volcanic area and it was a new and interesting experience.
   One, because it was my first solo mountaineering experience in a remote and unfamiliar terrain/vegetation and second, because above 2000m everything is wet and trails are getting slippery and the higher you go the jungle gets ticker and ticker.

** Must see
   I would say that there are 2 MUST SEE things in Bali, one is a rice terrace and second is a volcano/caldera. I've checked the first but unfortunately not the second.

   As far as rice terraces go:
   1. Jatiluwih - the biggest, the most beautiful and less touristy, a bit far away, central-north part of the island.
   2. Tegalalang - the most famous one and crowded, very close to Ubud

** Travel tip
   And finally here are 3 simple rules to survive in hot and humid climate and walk around like a boss not like a wet dog:

   1. turn the fucking AC off - moving in and out of AC-ing area is the worst
   2. take hot showers instead of cold ones - its a false impression of temporary cooling
   3. drink hot tea and water at room temperature
