#+title: Password management with Bitwarden
#+subtitle: Productivity
#+date:   2019-08-12
#+tags[]: password-management bitwarden linux brave open-source

The very first problem you encounter when moving from one platform to another is password migration. Being an Apple user for so many years it was natural to leverage their tools and store my passwords in iCloud.

Now, since I am not big fan of commercial password managers like LastPass, 1Password, etc, I needed to find new tool that satisfy my needs and criteria:

- it has to be open-source and free
- available on all platforms: Linux/Mac and Android/iOS
- browser agnostic since my main browser is [[https://brave.com/][Brave]] but I also open Firefox/Safari once in a while
- seamless integration with mobile/desktop apps to select the password without leaving the current app
- CLI and/or web interface to be able to do all kind of password hygiene

And the sole winner is [[https://bitwarden.com][Bitwarden]], an open-source and free app / service that you can use it in two ways:
1. you can deploy the web app and manage it by yourself
2. or use their free online service


So far so good, the only remaining problem is importing all passwords from Apple's iCloud. Even if Bitwarden has importers from all existing password managers or browsers it does not support Safari/iCloud because of Apple's closed ecosystem and policy but here is how to do it:

- Download and unzip [[https://www.dropbox.com/sh/a3skeey2zqimdlv/AAD87q6N_EJZ1YoPe5SA35a1a?dl=0][mrc-converter-suite]] into your Desktop
- Run the script `Get_Safari12_Passwords.applescript` using the script editor
- You should have a "pm_export.csv" file in your Desktop folder
- Git clone this [[https://gist.github.com/67ad186e5a89a11fc404832620a8b48f.git][Gist]] into "bitwarden.rb" file and make it executable
- Run 'bitwarden.rb'
- You should have a "bitwarden.csv" file in your current directory
- Import it to Bitwarden and you are all set

Just in case the above steps do not work or you do not trust those tools then do your own research and check [[https://discussions.agilebits.com/discussion/30286/mrcs-convert-to-1password-utility/p1][AgileBits excelent exporting tool]] and [[https://gist.github.com/rmondello/b933231b1fcc83a7db0b][other discussions]] on the same topic.

Keep your passwords safe. ALWAYS!
