#+title:  From Jekyll to Hugo
#+subtitle: Blog
#+date:   2019-04-18
#+tags[]: blog jekyll hugo org-mode gitlab emacs literate-programming

Since nobody wants to embrace the dark side of Wordpress anymore, the easiest way (that I knew of) to bootstrap a personal website was [[https://jekyllrb.com][Jekyll]] and [[https://www.netlify.com][Netlify]].
I am a huge advocate of getting things done fast, no fluff, just real stuff and this is what I did, but quite soon I realized that static Jekyll is not enough anymore and I needed to find new home.

Well, the old/new kid in town is called [[https://gohugo.io][Hugo]] and works like a charm with [[https://about.gitlab.com/product/pages/][GitLab Pages]], they even have a [[https://gitlab.com/pages/hugo][project template]]  for it. Just create a new project based on that template, name it "USERNAME.gitlab.io" and this is it, you've got yourself a deployable site.

Now, there are many PROs/CONs but for me the main reason for this move is because Hugo supports [[https://orgmode.org][Org-mode]] out-of-the-box.
For those who don't know what org-mode is, I tell you, is the only organization/word/excel/presentation tool that you always needed.

You can still access the [[https://icostan.github.io][old site]] but from now on we'll take full advantage of literate blogging with Org-mode / Hugo and GitLab pages.

More information about literate blogging in a new post. Stay tuned.
